03f9e63dd117122e2042d5dd3789ce368597ded05d6b1976baf7a3fd6c182de9

https://api.odcloud.kr/api/15070282/v1/uddi:00e5cb5a-ecdf-4190-a499-ba3a6b2a8db9?page=1&perPage=10&returnType=xml&serviceKey=03f9e63dd117122e2042d5dd3789ce368597ded05d6b1976baf7a3fd6c182de9

In [6]:
# 필요한 라이브러리 import 하기
import requests
import json

# Open API Key를 포함한 url 설정
url = 'https://api.odcloud.kr/api/15070282/v1/uddi:00e5cb5a-ecdf-4190-a499-ba3a6b2a8db9?page=1&perPage=10&serviceKey=03f9e63dd117122e2042d5dd3789ce368597ded05d6b1976baf7a3fd6c182de9'

# url에 접속 후 데이터 불러오기
response = requests.get(url)

# 불러온 데이터 확인하기
contents = response.text
print(contents)

{"currentCount":10,"data":[{"경상자수":"8635","부상신고자수":"757","사고건수":"18390","사고유형_대분류":"차대사람","사고유형_중분류":"횡단중","사망자수":"794","중상자수":"9403"},{"경상자수":"2575","부상신고자수":"276","사고건수":"4742","사고유형_대분류":"차대사람","사고유형_중분류":"차도통행중","사망자수":"205","중상자수":"1888"},{"경상자수":"1989","부상신고자수":"268","사고건수":"3196","사고유형_대분류":"차대사람","사고유형_중분류":"길가장자리구역통행중","사망자수":"69","중상자수":"1013"},{"경상자수":"1281","부상신고자수":"156","사고건수":"2194","사고유형_대분류":"차대사람","사고유형_중분류":"보도통행중","사망자수":"41","중상자수":"893"},{"경상자수":"9750","부상신고자수":"1253","사고건수":"16726","사고유형_대분류":"차대사람","사고유형_중분류":"기타","사망자수":"334","중상자수":"6319"},{"경상자수":"7424","부상신고자수":"576","사고건수":"6554","사고유형_대분류":"차대차","사고유형_중분류":"정면충돌","사망자수":"234","중상자수":"3750"},{"경상자수":"88548","부상신고자수":"7734","사고건수":"76234","사고유형_대분류":"차대차","사고유형_중분류":"측면충돌","사망자수":"545","중상자수":"24422"},{"경상자수":"54788","부상신고자수":"3964","사고건수":"36615","사고유형_대분류":"차대차","사고유형_중분류":"추돌","사망자수":"404","중상자수":"10392"},{"경상자수":"43999","부상신고자수":"4598","사고건수":"40079","사고유형_대분류":"차대차","사고유형_중분류":"기타","사망자수":"320","중상자수":"11479"},{"경상자수":"3027","부상신고자수":"129","사고건수":"2517","사고유형_대분류":"차대차","사고유형_중분류":"후진중충돌","사망자수":"2","중상자수":"307"}],"matchCount":17,"page":1,"perPage":10,"totalCount":17}

In [7]:
# 불러온 데이터를 json 형태로 변경
json_data = json.loads(contents)
print(json_data)
print()

print('데이터타입:', type(json_data)) #json타입 확인

{'currentCount': 10, 'data': [{'경상자수': '8635', '부상신고자수': '757', '사고건수': '18390', '사고유형_대분류': '차대사람', '사고유형_중분류': '횡단중', '사망자수': '794', '중상자수': '9403'}, {'경상자수': '2575', '부상신고자수': '276', '사고건수': '4742', '사고유형_대분류': '차대사람', '사고유형_중분류': '차도통행중', '사망자수': '205', '중상자수': '1888'}, {'경상자수': '1989', '부상신고자수': '268', '사고건수': '3196', '사고유형_대분류': '차대사람', '사고유형_중분류': '길가장자리구역통행중', '사망자수': '69', '중상자수': '1013'}, {'경상자수': '1281', '부상신고자수': '156', '사고건수': '2194', '사고유형_대분류': '차대사람', '사고유형_중분류': '보도통행중', '사망자수': '41', '중상자수': '893'}, {'경상자수': '9750', '부상신고자수': '1253', '사고건수': '16726', '사고유형_대분류': '차대사람', '사고유형_중분류': '기타', '사망자수': '334', '중상자수': '6319'}, {'경상자수': '7424', '부상신고자수': '576', '사고건수': '6554', '사고유형_대분류': '차대차', '사고유형_중분류': '정면충돌', '사망자수': '234', '중상자수': '3750'}, {'경상자수': '88548', '부상신고자수': '7734', '사고건수': '76234', '사고유형_대분류': '차대차', '사고유형_중분류': '측면충돌', '사망자수': '545', '중상자수': '24422'}, {'경상자수': '54788', '부상신고자수': '3964', '사고건수': '36615', '사고유형_대분류': '차대차', '사고유형_중분류': '추돌', '사망자수': '404', '중상자수': '10392'}, {'경상자수': '43999', '부상신고자수': '4598', '사고건수': '40079', '사고유형_대분류': '차대차', '사고유형_중분류': '기타', '사망자수': '320', '중상자수': '11479'}, {'경상자수': '3027', '부상신고자수': '129', '사고건수': '2517', '사고유형_대분류': '차대차', '사고유형_중분류': '후진중충돌', '사망자수': '2', '중상자수': '307'}], 'matchCount': 17, 'page': 1, 'perPage': 10, 'totalCount': 17}

데이터타입: <class 'dict'>

In [8]:
# 필요한 값만 추출하기
data = json_data['data']

# Dataframe으로 만들기
import pandas as pd
df = pd.json_normalize(data)

df

    경상자수 부상신고자수   사고건수 사고유형_대분류    사고유형_중분류 사망자수   중상자수
0   8635    757  18390     차대사람         횡단중  794   9403
1   2575    276   4742     차대사람       차도통행중  205   1888
2   1989    268   3196     차대사람  길가장자리구역통행중   69   1013
3   1281    156   2194     차대사람       보도통행중   41    893
4   9750   1253  16726     차대사람          기타  334   6319
5   7424    576   6554      차대차        정면충돌  234   3750
6  88548   7734  76234      차대차        측면충돌  545  24422
7  54788   3964  36615      차대차          추돌  404  10392
8  43999   4598  40079      차대차          기타  320  11479
9   3027    129   2517      차대차       후진중충돌    2    307

In [9]:
import requests
import pandas as pd

all_data = []

for page in range(1, 20):  # 페이지 반복
    url = f"https://api.odcloud.kr/api/15070282/v1/uddi:00e5cb5a-ecdf-4190-a499-ba3a6b2a8db9?page={page}&perPage=1000&returnType=json&serviceKey=03f9e63dd117122e2042d5dd3789ce368597ded05d6b1976baf7a3fd6c182de9"

    response = requests.get(url)
    json_data = response.json()

    data = json_data['data']
    all_data.extend(data)

df = pd.DataFrame(all_data)
print(len(df))

17

https://apis.data.go.kr/1360000/WthrWrnInfoService/getPwnStatus?serviceKey=03f9e63dd117122e2042d5dd3789ce368597ded05d6b1976baf7a3fd6c182de9&pageNo=1&numOfRows=10&dataType=XML

In [10]:
# 기상청 기상 특보 정보 가져오기
# 필요한 라이브러리 import 하기
import requests
import json
import urllib3

#warnings 메시지 출력하지 않도록 설정
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Open API Key를 포함한 url 설정
url = 'https://apis.data.go.kr/1360000/WthrWrnInfoService/getPwnStatus?serviceKey=03f9e63dd117122e2042d5dd3789ce368597ded05d6b1976baf7a3fd6c182de9&pageNo=1&numOfRows=10&dataType=JSON'

response = requests.get(url , verify=False)
contents = response.text
print(contents)

{"response":{"header":{"resultCode":"00","resultMsg":"NORMAL_SERVICE"},"body":{"dataType":"JSON","items":{"item":[{"other":"o 부산동부 : 기장군, 해운대구, 수영구, 남구\r\no 부산중부 : 금정구, 북구, 동래구, 연제구, 부산진구, 사상구\r\no 부산서부 : 강서구, 사하구, 영도구, 서구, 동구, 중구\r\no 울산동부 : 북구, 동구, 중구, 남구\r\no 울산서부 : 울주군","t6":"o 대설주의보 : 강원도(태백, 강원북부산지, 강원중부산지, 강원남부산지)","t7":"(1) 풍랑 예비특보\r\no 03월 12일 밤(18시~24시) : 제주도남쪽바깥먼바다\r\no 03월 13일 새벽(00시~06시) : 동해남부전해상, 남해동부안쪽먼바다, 남해동부바깥먼바다, 제주도남동쪽안쪽먼바다\r\no 03월 13일 오전(06시~12시) : 동해중부안쪽먼바다, 동해중부바깥먼바다\r\n(2) 강풍 예비특보\r\no 03월 13일 오전(06시~12시) : 울릉도.독도","tmEf":"202603121000","tmFc":202603121000,"tmSeq":98}]},"pageNo":1,"numOfRows":10,"totalCount":1}}}

In [11]:
# 불러온 데이터를 json 형태로 변경
json_data = json.loads(contents)
print(json_data)
print()

print('데이터타입:', type(json_data)) # json 타입 확인

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL_SERVICE'}, 'body': {'dataType': 'JSON', 'items': {'item': [{'other': 'o 부산동부 : 기장군, 해운대구, 수영구, 남구\r\no 부산중부 : 금정구, 북구, 동래구, 연제구, 부산진구, 사상구\r\no 부산서부 : 강서구, 사하구, 영도구, 서구, 동구, 중구\r\no 울산동부 : 북구, 동구, 중구, 남구\r\no 울산서부 : 울주군', 't6': 'o 대설주의보 : 강원도(태백, 강원북부산지, 강원중부산지, 강원남부산지)', 't7': '(1) 풍랑 예비특보\r\no 03월 12일 밤(18시~24시) : 제주도남쪽바깥먼바다\r\no 03월 13일 새벽(00시~06시) : 동해남부전해상, 남해동부안쪽먼바다, 남해동부바깥먼바다, 제주도남동쪽안쪽먼바다\r\no 03월 13일 오전(06시~12시) : 동해중부안쪽먼바다, 동해중부바깥먼바다\r\n(2) 강풍 예비특보\r\no 03월 13일 오전(06시~12시) : 울릉도.독도', 'tmEf': '202603121000', 'tmFc': 202603121000, 'tmSeq': 98}]}, 'pageNo': 1, 'numOfRows': 10, 'totalCount': 1}}}

데이터타입: <class 'dict'>

In [12]:
# 필요한 데이터만 출력
import pandas as pd
res = pd.DataFrame(json_data['response']['body']['items']['item'])
res

,other,t6,t7,tmEf,tmFc,tmSeq
0,"o 부산동부 : 기장군, 해운대구, 수영구, 남구\r\no 부산중부 : 금정구, 북...","o 대설주의보 : 강원도(태백, 강원북부산지, 강원중부산지, 강원남부산지)",(1) 풍랑 예비특보\r\no 03월 12일 밤(18시~24시) : 제주도남쪽바깥먼...,202603121000,202603121000,98

업비트